export const SIGN_IN_INIT = 'SIGN_IN_INIT'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'

export const FETCH_USERS_INIT = 'FETCH_USERS_INIT'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'

export const GET_CHATS_INIT = 'GET_CHATS_INIT'
export const GET_CHATS_FAIL = 'GET_CHAT_FAIL'
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS'

export const GET_PRIVATE_CHAT_INITIATE = 'GET_PRIVATE_CHAT_INITIATE'
export const GET_PRIVATE_CHAT_FAIL = 'GET_PRIVATE_CHAT_FAIL'
export const GET_PRIVATE_CHAT_SUCCESS = 'GET_PRIVATE_CHAT_SUCCESS'

export const GET_MESSAGES_INIT = 'GET_MESSAGES_INIT'
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL'
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS'