export const SIGN_IN_INIT = 'SIGN_IN_INIT'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'

export const FETCH_USERS_INIT = 'FETCH_USERS_INIT'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'